// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd4TrorD9OzB6xIP7XI9FFf6M-jeLLU5c',
    appId: '1:160603350210:web:1c0afdb2ddbe171463475b',
    messagingSenderId: '160603350210',
    projectId: 'flash-chat-54e78',
    authDomain: 'flash-chat-54e78.firebaseapp.com',
    storageBucket: 'flash-chat-54e78.appspot.com',
    measurementId: 'G-TPMV0RYCMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX_Wezwlw_ZiGsbh_7kLBfspFIrdNHCDA',
    appId: '1:160603350210:android:a863c1e99900c62663475b',
    messagingSenderId: '160603350210',
    projectId: 'flash-chat-54e78',
    storageBucket: 'flash-chat-54e78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqgWcVTTUgRY1ps3L7eU0ujvTp93oWOB0',
    appId: '1:160603350210:ios:9bb2c968e110c93663475b',
    messagingSenderId: '160603350210',
    projectId: 'flash-chat-54e78',
    storageBucket: 'flash-chat-54e78.appspot.com',
    iosClientId: '160603350210-pmobdi9u924a6257bjks72f8rr7mn165.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqgWcVTTUgRY1ps3L7eU0ujvTp93oWOB0',
    appId: '1:160603350210:ios:9bb2c968e110c93663475b',
    messagingSenderId: '160603350210',
    projectId: 'flash-chat-54e78',
    storageBucket: 'flash-chat-54e78.appspot.com',
    iosClientId: '160603350210-pmobdi9u924a6257bjks72f8rr7mn165.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );
}
